- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/test/id_rsa"
  pre_tasks:
  - name: Update dnf
    become: true
    ansible.builtin.dnf:
      name: "*"
      state: latest
    tags:
      - install
      - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git.yml
