- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    source_api: "./.zshexports"
    dest_api: "{{ lookup('env', 'HOME') }}/.zshexports"
    ansible_user: "arne"
  pre_tasks:
  - name: Update package
    become: true
    when: "'arch' not in ansible_os_family"
    ansible.builtin.package:
      name: "*"
      state: latest
    tags:
      - install
      - core
  tasks:
    - name: Include Arch tasks
      include_tasks: tasks/arch.yml
      when: "'arch' in ansible_os_family"
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/git.yml
    - include: tasks/baseApps.yml
    - include: tasks/flatpak.yml
    - include: tasks/sway.yml
    - include: tasks/dotfiles.yml
