- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    source_api: "./.zshexports"
    dest_api: "{{ lookup('env', 'HOME') }}/.zshexports"
    ansible_user: "arne"
  tasks:
    - name: Non Arch tasks
      include_tasks: tasks/nonArch.yml
      when: "ansible_pkg_mgr != 'pacman'"
    - name: Include Arch tasks
      include_tasks: tasks/arch.yml
      when: "ansible_pkg_mgr == 'pacman'"
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/git.yml
    - include: tasks/baseApps.yml
    - include: tasks/flatpak.yml
    - include: tasks/sway.yml
    - include: tasks/dotfiles.yml
