- name: Install fuzzel and fira code on ubuntu
  become: true
  block:
    - name: Ensure fonts directory exists
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        state: directory
        mode: "0755"

    - name: Download Fira Code font archive
      ansible.builtin.get_url:
        url: "https://github.com/tonsky/FiraCode/releases/download/5.2/Fira_Code_v5.2.zip"
        dest: "Fira_Code_v5.2.zip"
        mode: '0644'

    - name: Extract Fira Code font archive
      ansible.builtin.unarchive:
        src: "Fira_Code_v5.2.zip"
        dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        remote_src: true
        extra_opts: [--no-same-owner]

    - name: Clear font cache
      ansible.builtin.command: fc-cache -f "{{ lookup('env', 'HOME') }}/.local/share/fonts"
