- name: Install extra repository
  become: true
  changed_when: true
  ansible.builtin.command: add-apt-repository universe -y

- name: Install dependencies for fuzzel
  become: true
  ansible.builtin.apt:
    name:
      - meson
      - ninja-build
      - librsvg2-dev
      - libx11-dev
      - libxtst-dev
      - libxkbfile-dev
      - libcairo2-dev
      - libpng-dev
      - wayland-protocols
    state: present

- name: Create build directory
  become: true
  ansible.builtin.file:
    path: ~/fuzzel/bld/release
    state: directory
    mode: '0755'

- name: Configure the build
  when_changed: false
  ansible.builtin.command: meson --buildtype=release -Denable-cairo=enabled -Dpng-backend=libpng -Dsvg-backend=librsvg ~/fuzzel/bld/release

- name: Build fuzzel
  when_changed: false
  ansible.builtin.command: ninja -C ~/fuzzel/bld/release

- name: Install fuzzel
  when_changed: false
  ansible.builtin.command: ninja -C ~/fuzzel/bld/release install
