- name: Update the system
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: Install required packages
  become: true
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - ansible
    - python

# Install yay AUR helper
- name: Install paru AUR helper
  become: true
  ansible.builtin.shell: |
    sudo pacman -S --needed git base-devel
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si --noconfirm
  args:
    creates: "/usr/bin/paru"
