- name: Install packages
  become: true
  ansible.builtin.dnf:
    name: ["tmux", "fzf", "neovim", "gimp", "tldr", "ripgrep"]
  tags:
    - install
    - productivity

- name: Install packages using Flatpak
  become: true
  flatpak:
    name: com.github.wez.wezterm
    state: present
    remote: flathub
  tags:
    - install
    - productivity
