- name: Install packages
  become: true
  ansible.builtin.dnf:
    name: ["tmux", "fzf", "neovim", "gimp", "tldr", "ripgrep"]
  tags:
    - install
    - productivity

- name: Install languages
  become: true
  ansible.builtin.dnf:
    name: ["npm", "dnf", "go", "shellcheck", "luarocks", "g++", "make", "ansible-lint"]
  tags:
    - install
    - productivity
    - languages

# - name: Rust likes to be special
#   become: true
#   ansible.builtin.command: /bin/bash -o pipefail -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y"
#   args:
#     creates: /usr/local/bin/cargo
#   tags:
#     - install
#     - productivity
#     - languages
# - name: Install Deno
#   become: true
#   ansible.builtin.command: /bin/bash -o pipefail -c "curl -fsSL https://deno.land/x/install/install.sh | sh"
#   args:
#     creates: /usr/local/bin/deno
#   tags:
#     - install
#     - productivity
#     - languages

- name: Check if deno is installed
  changed_when: false
  ansible.builtin.command: -v deno
  register: deno_exists
  ignore_errors: true
  tags:
    - install
    - productivity
    - languages

- name: Download Installer
  when: deno_exists is failed
  ansible.builtin.get_url:
    url: https://deno.land/x/install/install.sh
    dest: /tmp/sh.deno.rs
    mode: '0755'
    force: 'yes'
  tags:
    - deno
    - install
    - productivity
    - languages

- name: Install deno
  when: cargo_exists is failed
  changed_when: false
  ansible.builtin.command: /tmp/sh.deno.rs -y
  tags:
    - deno
    - install
    - productivity
    - languages

- name: Check if cargo is installed
  changed_when: false
  ansible.builtin.command: -v cargo
  register: cargo_exists
  ignore_errors: true
  tags:
    - install
    - productivity
    - languages

- name: Download Installer
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust
    - install
    - productivity
    - languages

- name: Install rust/cargo
  when: cargo_exists is failed
  changed_when: false
  ansible.builtin.command: /tmp/sh.rustup.rs -y
  tags:
    - rust
    - install
    - productivity
    - languages
