- name: Install packages
  become: true
  ansible.builtin.dnf:
    name: ["tmux", "fzf", "neovim", "gimp", "tldr", "ripgrep"]
  tags:
    - install
    - productivity

- name: Install languages
  become: true
  ansible.builtin.dnf:
    name: ["npm", "dnf", "go", "shellcheck", "luarocks", "g++", "make"]
  tags:
    - install
    - productivity
    - languages

# - name: Rust likes to be special
#   become: true
#   ansible.builtin.command: /bin/bash -o pipefail -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y"
#   args:
#     creates: /usr/local/bin/cargo
#   tags:
#     - install
#     - productivity
#     - languages

- name: Install Deno
  become: true
  ansible.builtin.command: /bin/bash -o pipefail -c "curl -fsSL https://deno.land/x/install/install.sh | sh"
  args:
    creates: /usr/local/bin/deno
  tags:
    - install
    - productivity
    - languages
