- name: Install packages
  become: true
  ansible.builtin.dnf:
    name: ["tmux", "fzf", "neovim", "gimp", "tldr", "ripgrep"]
  tags:
    - install
    - productivity

- name: Install WezTerm using Flatpak
  hosts: my_host
  become: true
  block:
    - name: Install Flatpak
      ansible.builtin.dnf:
        name: flatpak
        state: present

    - name: Add Flathub remote
      flatpak_remote:
        name: flathub
        url: https://flathub.org/repo/flathub.flatpakrepo
        state: present

    - name: Install WezTerm
      flatpak:
        name: com.github.wez.wezterm
        state: present
        remote: flathub
        install_deps: true
