- name: Install packages
  become: true
  ansible.builtin.dnf:
    name: ["tmux", "fzf", "neovim", "gimp", "tldr", "ripgrep"]
  tags:
    - install
    - productivity
- name: Install languages
  become: true
  ansible.builtin.dnf:
    name: ["npm", "dnf", "shellcheck", "stylua", "luarock", "deno", "g++", "make"]
  tags:
    - install
    - productivity
    - languages
