- name: Install packages
  become: true
  ansible.builtin.package:
    name:
      - tmux
      - fzf
      - neovim
      - gimp
      - tldr
      - ripgrep
      - htop
      - lsof
      - shutter
  tags:
    - install
    - productivity

- name: Install languages
  become: true
  ansible.builtin.package:
    name:
      - nodejs
      - npm
      - go
      - shellcheck
      - luarocks
      - make
      - ansible-lint
      - '{{ "python3-pip" if ansible_pkg_mgr != "pacman" else "" }}'
      - '{{ "g++" if ansible_pkg_mgr != "pacman" else "" }}'
  tags:
    - install
    - productivity
    - languages

- name: Check if deno is installed
  changed_when: false
  ansible.builtin.command: deno --version
  register: deno_exists
  ignore_errors: true
  tags:
    - install
    - productivity
    - languages

- name: Download Installer
  when: deno_exists is failed
  ansible.builtin.get_url:
    url: https://deno.land/x/install/install.sh
    dest: /tmp/sh.deno.rs
    mode: '0755'
    force: 'yes'
  tags:
    - deno
    - install
    - productivity
    - languages

- name: Install deno
  when: deno_exists is failed
  changed_when: false
  ansible.builtin.command: /bin/bash /tmp/sh.deno.rs
  tags:
    - deno
    - install
    - productivity
    - languages

- name: Check if cargo is installed
  changed_when: false
  ansible.builtin.command: cargo --version
  register: cargo_exists
  ignore_errors: true
  tags:
    - install
    - productivity
    - languages

- name: Download Installer
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust
    - install
    - productivity
    - languages

- name: Install rust/cargo
  when: cargo_exists is failed
  changed_when: false
  ansible.builtin.command: /bin/bash /tmp/sh.rustup.rs -y
  tags:
    - rust
    - install
    - productivity
    - languages
