- name: Installing stow
  become: true
  ansible.builtin.dnf:
    name: stow
    state: present
  tags:
    - install
    - dotfiles
    - stow

- name: Remove dotfiles folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/dotfiles"
    state: absent
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:arnevm123/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: true
    update: true
    accept_hostkey: true
    version: master
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  ansible.builtin.shell: cd $HOME/dotfiles && ./linux
  changed_when: false
  tags:
    - install
    - dotfiles
    - stow
