- name: Install Flatpak
  become: true
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Add Flathub remote
  become: true
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

- name: Install WezTerm
  become: true
  flatpak:
    name: org.wezfurlong.wezterm
    state: present
    remote: flathub
