- name: Install Flatpak
  become: true
  ansible.builtin.dnf:
    name: flatpak
    state: present

- name: Add Flathub remote
  become: true
  flatpak_remote:
    name: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

- name: Install WezTerm
  become: true
  flatpak:
    name: com.github.wez.wezterm
    state: present
    remote: flathub
    install_deps: true
