- name: Install Flatpak
  become: true
  ansible.builtin.package:
    name: flatpak
    state: present
  tags:
    - flatpak

- name: Add Flathub remote
  become: yes
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install WezTerm
  become: true
  flatpak:
    remote: flathub
    name: org.wezfurlong.wezterm
    state: present
  tags:
    - flatpak
