- name: Install applications used for sway setup 1
  become: true
  ansible.builtin.package:
    name:
      - sway
      - fuzzel
      - rofi
      - '{{ "wlogout" if ansible_pkg_mgr != "pacman" else "" }}'
      - '{{ "fira-code-fonts" if ansible_pkg_mgr != "pacman" else "ttf-fira-code" }}'
  tags:
    - install
    - sway
    - productivity

- name: Install wlogout
  become: true
  changed_when: false
  ansible.builtin.command: yay -S wlogout
  when: "ansible_pkg_mgr == 'pacman'"
  tags:
    - install
    - sway
    - productivity

- name: Install applications used for sway setup 2
  become: true
  ansible.builtin.package:
    name:
      - waybar
      - wl-clipboard
      - mpc
      - mpv
      - grim
      - slurp
  tags:
    - install
    - sway
    - productivity

- name: Install applications used for sway setup 3
  become: true
  ansible.builtin.package:
    name:
      - light
      - mako
      - ncmpcpp
      - pavucontrol
      - ranger
      - swaylock
      - swaybg
  tags:
    - install
    - sway
    - productivity
