- name: Install ZSH
  become: true
  ansible.builtin.dnf:
    name: zsh
    state: present
  changed_when: false
  tags: &tags_for_zsh_tasks ['install', 'productivity', 'dotfiles', 'zsh']

- name: Change shell to zsh
  become_user: arne
  ansible.builtin.shell: chsh -s $(which zsh)
  changed_when: false
  tags: *tags_for_zsh_tasks

- name: Check that the oh my zsh folder exists
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_dir
  changed_when: false
  tags: *tags_for_zsh_tasks

- name: Download Oh My Zsh installation script
  when: not ohmyzsh_dir.stat.exists
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install-oh-my-zsh.sh
    mode: 'u+x'

- name: Run Oh My Zsh installation script
  when: not ohmyzsh_dir.stat.exists
  ansible.builtin.script: /tmp/install-oh-my-zsh.sh --unattended

- name: Install zsh-autosuggestions
  when: not ohmyzsh_dir.stat.exists
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  changed_when: false
  tags: *tags_for_zsh_tasks

- name: Install zsh apikeys
  ansible.builtin.copy:
    src: "{{ source_api }}"
    dest: "{{ dest_api }}"
    mode: '0600'
  when: false
  tags: *tags_for_zsh_tasks
